[banny]
[bytebeat]
[defiler]
[django-cee-proto]
[dxv3]
[farr_tinyev]
[glitch]
[hjum]
[html5-cheatsheet]
[leveldb-test]
[listeningclub]
[markdown-cheatsheet-fi]
[mess]
[michelle]
[nocheese]
[pentu]
[poco]
[rust-glitch]
[shoop-checkoutfi]
[shoop-pugme]
[spi]
[stackspy]
[supersample]
[twitter-swagger-api-defs]
[ubuntu-gdk-pixbuf-pkg-bug]
[vw]
[yodel]
[dish]
[svgmap-to-imagemap]
[vagrant-ubuntu-core]
[config]
[ansible-test]
[project-timeline]

[foamy]
description = "Simpler SOAP for Python."
url = 'https://github.com/akx/foamy'
language = 'Python'
date = '2012-09-07'
category = 'Libraries'
status = 'Incomplete'


[Notifications]
description = "Some libre notification sounds."
url = 'https://github.com/akx/Notifications'
date = '2013-02 (and subsequent updates)'
category = 'Audio'

[noisykeys]
description = "A little C# app that mutes microphones when noisy keyboards are abound."
url = 'https://github.com/akx/noisykeys'
language = 'C#'
platform = "Windows"
date = '2013-03-18'
category = 'Audio'

[python-portmidi]
description = "Some MIDI/OSC stuff"
url = 'https://github.com/akx/python-portmidi'
language = 'Python'
date = '2013-05-14'
category = 'Audio'

[requiem]
description = "Silliest Debian/Ubuntu provisioning toolkit"
url = 'https://github.com/akx/requiem'
language = 'Python'
date = '2013-09-06'
category = 'Utilities'

[stateside]
description = "Layer comps for HTML."
url = 'https://github.com/akx/stateside'
language = 'JavaScript'
date = '2013-10-21'
category = 'Webdev'

[spotify-tools]
description = ""
url = 'https://github.com/akx/spotify-tools'
language = 'Python'
date = '2014-01-12'
category = 'Audio'

[hayes]
description = "Simpler Elasticsearch (for Django, and otherwise)"
url = 'https://github.com/akx/hayes'
language = 'Python/Django'
date = '2014-01-23'
category = 'Webdev'

[djembe]
description = "Django template toy environment (for learning!)"
url = 'https://github.com/akx/djembe'
language = 'Python/Django'
date = '2014-01-23'
category = 'Webdev'

[Remote]
description = "Remote system session manager for Windows"
url = 'https://github.com/akx/Remote'
language = 'C#'
date = '2014-01-24'
category = 'Utilities'

[bro-py]
description = "Unofficial Bropages.org Python client"
homepage = 'http://bropages.org/'
url = 'https://github.com/akx/bro-py'
language = 'Python'
date = '2014-01-25'
category = 'Utilities'

[ant1gravity-hearthstone-tier-lists]
description = "Parses Ant1gravity's Hearthstone tier list spreadsheets into a more greppable form."
url = 'https://github.com/akx/ant1gravity-hearthstone-tier-lists'
language = 'Python'
date = '2014-02-09'
category = 'Data'

[arpy]
description = "A Web MIDI arpeggiator/step sequencer thing."
url = 'https://github.com/akx/arpy'
homepage = 'http://akx.github.io/arpy/arpy.html'
language = 'JavaScript'
date = '2014-05-04'
category = 'Audio'

[minigradient-js]
description = "Mini-library for gradient interpolation"
url = 'https://github.com/akx/minigradient.js'
language = 'JavaScript'
date = '2014-05-15'
category = 'Libraries'

[ix]
description = "Stack-based image processing toy language"
url = 'https://github.com/akx/ix'
homepage = 'http://akx.github.io/ix'
language = 'JavaScript'
date = '2014-06-17'
category = 'Graphics'

[gravelly-js]
description = "Object-oriented API for generating SVG path strings"
url = 'https://github.com/akx/gravelly.js'
language = 'JavaScript'
date = '2014-07-16'
category = 'Libraries'

[git-kit]
description = "Some extension commands for git"
url = 'https://github.com/akx/git-kit'
language = 'Python'
date = '2014-07-28'
category = 'Utilities'

[stk-js]
description = "Hand-transforming the Synthesis ToolKit to JavaScript."
url = 'https://github.com/akx/stk.js'
language = 'JavaScript'
date = '2014-07-29'
category = 'Audio'

[duplica]
description = "A fast file duplicate finder in C#"
url = 'https://github.com/akx/duplica'
language = 'C#'
date = '2014-08-30'
category = 'Utilities'

[EFFTHATNOISE]
description = "A bytebeat livecoding environment."
homepage = 'http://akx.github.io/EFFTHATNOISE/'
url = 'https://github.com/akx/EFFTHATNOISE'
language = 'JavaScript'
date = '2014-09-04'
category = 'Audio'

[bk-suomi-menu]
description = "A menu for a fast food chain that only serves their menus as images."
homepage = 'http://akx.github.io/bk-suomi-menu/'
url = 'https://github.com/akx/bk-suomi-menu'
language = 'JavaScript'
date = '2014-10-01'
category = 'Data'

[glitch2]
description = "HTML5 Canvas glitch effect generator"
homepage = 'http://akx.github.io/glitch2/'
url = 'https://github.com/akx/glitch2'
language = 'JavaScript'
date = '2014-12-27'
category = 'Graphics'

[picotable]
description = "Tiny, fast data grid built on Mithril.js"
url = 'https://github.com/akx/picotable'
language = 'JavaScript'
date = '2015-02-20'
category = 'Webdev'

[unimap]
description = "An Unicode map in the browser!"
homepage = 'http://akx.github.io/unimap/unimap.html'
url = 'https://github.com/akx/unimap'
language = 'JavaScript'
date = '2015-03-26'
category = 'Utilities'

[smh]
description = "just a little file-watcher-child-process-reloader."
url = 'https://github.com/akx/smh'
language = 'JavaScript'
date = '2015-04-02'
category = 'Utilities'



[dot3k-c]
description = "A C library for Pimoroni's Display-O-Tron 3000"
url = 'https://github.com/akx/dot3k-c'
language = 'C'
date = '2015-04-16'
category = 'Libraries'


[caldera]
description = "Utilities for distilling data from the Unicode CLDR"
url = 'https://github.com/akx/caldera'
language = 'Python'
date = '2015-04-30'
category = 'Utilities'

[band-stars]
description = "Band Stars Data"
homepage = 'http://akx.github.io/band-stars/'
url = 'https://github.com/akx/band-stars'
language = 'JavaScript'
date = '2015-05-09'
category = 'Data'

[license-grep]
description = "Figure out licenses for the current Python/NPM/Bower environment"
url = 'https://github.com/akx/license-grep'
language = 'Python'
date = '2015-06-02'
category = 'Utilities'

[slacktrack]
description = "Lazy Slack archiver"
url = 'https://github.com/akx/slacktrack'
language = 'JavaScript'
date = '2015-06-09'
category = 'Other stuff'


[tcd]
name = "tcd (aka tiny colorful dots)"
description = "Tiny Colorful Dots - a simple, small, fast light color picker"
url = 'https://github.com/akx/tcd'
language = 'C#'
platform = "Windows"
download = "https://github.com/akx/tcd/releases/latest"
date = '2015-07-05'
category = 'Utilities'


[tune2youtube]
description = "Converts music to video with cover art, ready to upload to YouTube."
url = 'https://github.com/akx/tune2youtube'
language = 'Python'
date = '2015-07-13 (cleaned from older sources)'
category = 'Audio'

[maskin]
description = "A cross-modulating synth sequencer toy."
homepage = 'http://akx.github.io/maskin/'
url = 'https://github.com/akx/maskin'
language = 'JavaScript'
date = '2015-07-14'
category = 'Audio'

[GRL-LaserTag]
description = "Graffiti Research Labs' LASER Tag, with updates"
url = 'https://github.com/akx/GRL-LaserTag'
language = 'C'
date = '2015-07-23'
category = 'Graphics'

[ltag]
description = """
Laser graffiti ([L.A.S.E.R. Tag](http://www.graffitiresearchlab.com/blog/projects/laser-tag/)) software.

Built out of frustration with the architecture and performance of the GRL's software.

Includes support for single-touch TUIO input in addition to built-in OpenCV blob tracking.
"""
download = "https://github.com/akx/ltag/releases/latest"
url = 'https://github.com/akx/ltag'
language = 'C#'
date = '2015-07-26'
category = 'Graphics'


[slack-topical]
description = "Topic-augmenting bot for Slack"
url = 'https://github.com/akx/slack-topical'
language = 'JavaScript'
date = '2015-08-13'
category = 'Other stuff'

[geoseq]
description = "Geometry-based web audio sequencer"
homepage = 'http://akx.github.io/geoseq/'
url = 'https://github.com/akx/geoseq'
language = 'JavaScript'
date = '2015-09-06'
category = 'Audio'


[npdeck]
description = """
Extract "Now playing" from Winamp/Foobar2000 into text files and/or images.

Built for OBS-Studio, but could be useful for other uses.
"""
url = 'https://github.com/akx/npdeck'
language = 'C#/WPF'
platform = "Windows"
date = '2015-09-20'
category = 'Utilities'

[fxfxfx]
description = "Old-skool noise/sound effect generator for Windows"
url = 'https://github.com/akx/fxfxfx'
download = 'https://github.com/akx/fxfxfx/releases/latest'
platform = 'Windows'
language = 'C#'
date = '2010-10'
category = 'Audio'

[chopshop]
description = "Chops WAV files into slices of equal count or duration"
url = 'https://github.com/akx/chopshop'
download = 'https://github.com/akx/chopshop/releases/latest'
platform = 'Windows'
language = 'C#'
date = '2010-04'
category = 'Audio'

[qta]
description = "Pretty particle chamber simulation (Windows)"
url = 'https://github.com/akx/qta'
download = 'https://github.com/akx/qta/releases/latest'
language = 'C#'
platform = "Windows"
date = '2009-12'
category = 'Graphics'

[cosmicdrone]
description = "Subtly oscillating drone machine."
homepage = 'http://akx.github.io/cosmicdrone'
url = 'https://github.com/akx/cosmicdrone'
language = 'JavaScript'
date = '2015-10-08'
category = 'Audio'

[reascale-js]
description = "Reads Reascale files, outputs JavaScript. Built as a dependency of Chromon."
url = 'https://github.com/akx/reascale-js'
language = 'JavaScript'
date = '2015-10-10'
category = 'Audio'

[chromon]
description = "Stochastic scale-based sequencing with a sampler"
homepage = 'http://akx.github.io/chromon'
url = 'https://github.com/akx/chromon'
language = 'JavaScript'
date = '2015-10-10'
category = 'Audio'

[islands]
description = "JavaScript island map generator (circa 2013)"
url = 'https://github.com/akx/islands'
language = 'JavaScript'
date = '2013'
category = 'Graphics'

[peep]
description = """
What if you could only see just a little bit of the web?

A bookmarklet I made for a friend who was working with visually impaired people,
with the idea that you could show how hard it is to navigate the Internet if you can
only see a tiny bit of each page.
"""
homepage = 'http://akx.github.io/peep'
url = 'https://github.com/akx/peep'
language = 'HTML'
date = '2011'
category = 'Other stuff'

[mashed]
description = "Full screen JPEG glitch"
homepage = 'http://akx.github.io/mashed'
url = 'https://github.com/akx/mashed'
language = 'JavaScript'
date = '2013'
category = 'Graphics'

[circgen]
description = "\"Circuit\" image generator I once wrote for a friend."
homepage = 'http://akx.github.io/circgen'
url = 'https://github.com/akx/circgen'
language = 'JavaScript'
date = '2015-10-14'
category = 'Graphics'

[lauo]
description = "Incomplete yet functional fast file launcher (like Launchy) for Windows"
url = 'https://github.com/akx/lauo'
language = 'C#'
platform = 'Windows'
date = '2012'
category = 'Utilities'

[evotd]
description = "EvoTD, my contribution to Ludum Dare 24 (2012)"
homepage = 'http://akx.github.io/evotd'
url = 'https://github.com/akx/evotd'
language = 'JavaScript'
date = '2012'
category = 'Games'

[xerador]
description = "A name generator"
homepage = 'http://akx.github.io/xerador'
url = 'https://github.com/akx/xerador'
language = 'JavaScript'
date = '2015-11-01'
category = 'Other stuff'

[abyss]
description = "A statistical profiler and flamechart generator for Python"
url = 'https://github.com/akx/abyss'
language = 'Python'
date = '2015-12-15'
category = 'Development'

[pytest-repeat]
description = "Repeat py.tests."
url = 'https://github.com/akx/pytest-repeat'
language = 'Python'
date = '2015-12-29'
category = 'Development'

[nutritious]
description = "Normalized nutrition data"
url = 'https://github.com/akx/nutritious'
language = 'JavaScript'
date = '2016-01-10'
category = 'Data'

[mklocale]
description = "A small utility to download and combine translations"
url = 'https://github.com/akx/mklocale'
language = 'Python'
date = '2016-02-03'
category = 'Development'

[ttf-embed]
description = "A fork of Tom7's ttf-embed"
homepage = 'http://carnage-melon.tom7.org/embed/'
url = 'https://github.com/akx/ttf-embed'
language = 'C'
date = '2016-02-18'
category = 'Utilities'

[d2d]
description = "Data-to-Data transformer tool"
url = 'https://github.com/akx/d2d'
language = 'JavaScript'
date = '2016-04-01'
category = 'Development'

[touchy]
description = "Node.js server to translate OSX touchpad data to web sockets"
url = 'https://github.com/akx/touchy'
language = 'JavaScript'
date = '2016-04-02'
category = 'Other stuff'

[diskbunny]
description = "A :rabbit: for your :file_folder:"
url = 'https://github.com/akx/diskbunny'
language = 'JavaScript'
date = '2016-04-10'
category = 'Other stuff'

[umbra]

[homekit]
description = "Backend & frontend for a tablet-based home \"automation\" display"
url = 'https://github.com/akx/homekit'
language = 'JavaScript'
date = '2016-05-08'
category = 'IoT'

[mixdesk]
description = "Electron-based Mixcloud.com client"
url = 'https://github.com/akx/mixdesk'
language = 'JavaScript'
date = '2016-05-13'
category = 'Utilities'

[redwall]
description = "Download wallpapers from Reddit"
url = 'https://github.com/akx/redwall'
language = 'JavaScript'
date = '2016-05-31'
category = 'Utilities'

[iotlog]
description = "Tiny HTTP IoT data logger"
url = 'https://github.com/akx/iotlog'
language = 'JavaScript'
date = '2016-06-18'
category = 'IoT'

[foofdf]
description = "Simple tool to fill PDF forms based on FDF/XFDF/JSON"
url = 'https://github.com/akx/foofdf'
language = 'Java'
date = '2016-06-22'
category = 'Development'

[pizzeriat]
description = "Data about Finnish pizzerias"
url = 'https://github.com/akx/pizzeriat'
language = 'Python'
date = '2016-08-14'
category = 'Other stuff'

[docker-mapnik]
description = "Mapnik Docker container with Node and Python bindings"
url = 'https://github.com/akx/docker-mapnik'
language = 'Shell'
date = '2016-08-22'
category = 'Development'

[mlog]

[django-i18nkit]
description = "Making Django internationalization a little easier"
url = 'https://github.com/akx/django-i18nkit'
language = 'Python'
date = '2016-08-29'
category = 'Development'

[django-soft-choice-fields]
description = "Choice fields that don't record the actual choices lists in migrations."
url = 'https://github.com/akx/django-soft-choice-fields'
language = 'Python'
date = '2016-09-12'
category = 'Development'

[espy]
description = "Elasticsearch introspection utility"
url = 'https://github.com/akx/espy'
language = 'Python'
date = '2016-09-16'
category = 'Development'

[pyttipannu]
description = "Simple recipe aggregator project used for an internal training at Anders."
url = 'https://github.com/akx/pyttipannu'
language = 'Python'
date = '2016-09-23'
category = 'Development'

[my-video]
description = "Dynamic kinetic typography video for Childish Gambino's Put It In My Video"
homepage = 'https://akx.github.io/my-video'
url = 'https://github.com/akx/my-video'
language = 'JavaScript'
date = '2016-10-01'
category = 'Graphics'

[glmr]
description = "Canvas trails/drawing hack."
homepage = 'https://akx.github.io/glmr/'
url = 'https://github.com/akx/glmr'
language = 'HTML'
date = '2011-11'
category = 'Graphics'

[tritri]
description = "Kinetic triangles in SVG"
homepage = [
    'https://akx.github.io/tritri/tritri.html',
    'https://akx.github.io/tritri/tritri2.html',
    'https://akx.github.io/tritri/tritr3.html'
   ]
url = 'https://github.com/akx/tritri'
language = 'JavaScript'
date = '2014-07'
category = 'Graphics'

[runway]
description = "Declarative budgeting"
url = 'https://github.com/akx/runway'
language = 'JavaScript'
date = '2016-10-10'
category = 'Other stuff'

[reddit-tv]
description = "Infinite distraction, powered by /r/youtubehaiku"
homepage = 'https://akx.github.io/reddit-tv'
url = 'https://github.com/akx/reddit-tv'
language = 'JavaScript'
date = '2016-10-10'
category = 'Internet'

[uni]
description = "Unicode map on the command line!"
url = 'https://github.com/akx/uni'
language = 'Python'
date = '2016-10-27'
category = 'Other stuff'

[neki]

[words]
description = "A word finder."
homepage = 'https://akx.github.io/words/'
url = 'https://github.com/akx/words'
language = 'JavaScript'
date = '2016-11-12'
category = 'Games'

[veryloudsite]
description = "#radix_challenge hack for Junction 2016"
homepage = 'http://veryloud.site/'
url = 'https://github.com/akx/veryloudsite'
language = 'CSS'
date = '2016-11-26'
category = 'Audio'

[nodemuki]

[sshw]
description = "Goodifying terminals for SSH!"
url = 'https://github.com/akx/sshw'
language = 'Python'
date = '2017-02-01'
category = 'Other stuff'

[summarize-sync-io]
description = "Summarize Node.js --trace-sync-io logs"
url = 'https://github.com/akx/summarize-sync-io'
language = 'JavaScript'
date = '2017-02-10'
category = 'Other stuff'

[rahe]
description = "Retrospective personal budgeting"
url = 'https://github.com/akx/rahe'
language = 'JavaScript'
date = '2017-02-23'
category = 'Other stuff'

[gifify]
description = "A tiny Python script for making high-quality GIFs out of videos."
url = 'https://github.com/akx/gifify'
language = 'Python'
date = '2017-03-13'
category = 'Graphics'

[tinydynip]
description = "Yet another DynIP updater"
url = 'https://github.com/akx/tinydynip'
language = 'Python'
date = '2017-03-15'
category = 'Other stuff'

[webpack-css-bundle-example]
description = "Webpack2 multiple entrypoint CSS extraction example for Koodiklinikka"
url = 'https://github.com/akx/webpack-css-bundle-example'
language = 'JavaScript'
date = '2017-04-04'
category = 'Other stuff'


[yle-kuntavaalit-2017-data]
description = "Data about the 2017 Finnish municipal elections, scraped from yle.fi"
url = 'https://github.com/akx/yle-kuntavaalit-2017-data'
language = 'Python'
date = '2017-04-09'
category = 'Other stuff'

[docker-chrome-dev]
description = "Headless Google Chrome! In a container! On a whale!"
url = 'https://github.com/akx/docker-chrome-dev'
language = 'Docker'
date = '2017-04-18'
category = 'Other stuff'

[rd]
description = "Reddit downloader/video link detector"
url = 'https://github.com/akx/rd'
language = 'Python'
date = '2017-04-21'
category = 'Web'

[funfun]
description = "Easing function generator and visualizer"
homepage = 'https://akx.github.io/funfun/'
url = 'https://github.com/akx/funfun'
language = 'JavaScript'
date = '2017-04-21'
category = 'Tools'

[demystifying-webpack]
description = "Demystifying Webpack â€“ presentation & code"
homepage = 'https://akx.github.io/demystifying-webpack/'
url = 'https://github.com/akx/demystifying-webpack'
language = 'JavaScript'
date = '2017-04-27'
category = 'Presentations'

[lepo]
description = "Contract-first REST APIs in Django"
url = 'https://akx.github.io/lepo'
language = 'Python'
date = '2017-05-12'
category = 'Development'

[proj4leaflet-test]

[suppisyn]
description = "Stochastic sampling synthesizer from a friend's voice"
url = 'https://akx.github.io/suppisyn/'
language = 'JavaScript'
date = '2017-05-26'
category = 'Audio'

[neat]
description = "beta.eat.fi data visualizer (proof of concept that it doesn't have to be slow)"
url = 'https://github.com/akx/neat'
language = 'JavaScript'
date = '2017-05-31'
category = 'Other stuff'

[billtag]
description = "Hackery bill splitting"
url = 'https://github.com/akx/billtag'
language = 'Python'
date = '2017-06-05'
category = 'Tools'

[cookiecutter-js-sketch]
description = "Cookiecutter template for live-reloading JS sketches"
url = 'https://github.com/akx/cookiecutter-js-sketch'
language = 'JavaScript'
date = '2017-06-06'
category = 'Development'

[watercolour]
description = "Watercolour generator"
url = 'https://github.com/akx/watercolour'
language = 'JavaScript'
date = '2017-06-06'
category = 'Graphics'

[s3-dupes]
description = "S3 duplicate object detector & deletor"
url = 'https://github.com/akx/s3-dupes'
language = 'JavaScript'
date = '2017-06-22'
category = 'Tools'


